name: FIREBASE-DEPLOY

on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Build
        working-directory: ./functions
        run: yarn && yarn build
      - run: ls -la && pwd
      - uses: w9jds/firebase-action@master
        with:
          args: use next-js-practice1 && firebase deploy --debug --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
